### PR TITLE
Update mokee-build-targets

### PR DESCRIPTION
**Pull request by bthorne79**

### CODE REVIEW

**Comment by martincz** [comment]
Thanks, wait me a moment。
I'll create repository

**Comment by bthorne79** [comment]
thanks how do i lunch from build i cant figure yours out....
./mk d2spr right

**Comment by bthorne79** [comment]
i love it on my tab2 p3113

**Comment by mokeeopensource** [comment]
Give me some times.
When I finish repository create, you can exec:

. build/envsetup.shlunch mk_d2spr-userdebug
mka bacon

---

```
 Best Regards
 Martincz.Gao


 Email:martincz.gao@mokeetek.com
 Home:http://www.mokeetek.com
 Twitter:http://weibo.com/martincz


 魔趣科技(上海)有限公司
 Illustrating Your Mobile Life.
```

------------------ 原始邮件 ------------------
发件人: "bthorne79"; 
发送时间: 2013年7月19日(星期五) 上午6:35
收件人: "MoKee/android_vendor_mk"; 
主题: Re: [android_vendor_mk] Update mokee-build-targets (#1)

thanks how do i lunch from build i cant figure yours out....
 ./mk d2spr right

**Comment by martincz** [comment]
Hi, mate. You can repo sync source code now.

**Pull request merged**
